trigger:
-  development

# variables:
#   buildConfiguration: 'Release'

jobs:
- job: Android
  displayName: 'Build Andriod'
  pool:
    vmImage: 'macOS-latest'

  steps:
  - task: FlutterInstall@0

  - task: FlutterBuild@0
    inputs:
      target: apk
      projectDirectory: $(Build.SourcesDirectory)

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/build/app/outputs/flutter-apk'
      contents: 'app.apk'
      targetFolder: '$(build.artifactStagingDirectory)'
  
  - task: PublishBuildArtifacts@1
    inputs: 
      pathToPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: APK
      #publishLocation: 'Container' # Options: container, filePath
      # targetPath: $(Build.Repository.LocalPath)/build/app/outputs/flutter-apk/app.apk
      # artifactType: pipeline
  

- job: WEB
  displayName: 'WEB'
  pool:
    vmImage: 'macOS-latest'

  steps:
  - task: FlutterInstall@0

  - task: FlutterBuild@0
    inputs:
      target: web
      projectDirectory: $(Build.SourcesDirectory)

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/build/web'
      #contents: 'app.apk'
      targetFolder: '$(build.artifactStagingDirectory)'
  
  - task: PublishBuildArtifacts@1
    inputs: 
      pathToPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: WEB
      #publishLocation: 'Container' # Options: container, filePath
      # targetPath: $(Build.Repository.LocalPath)/build/app/outputs/flutter-apk/app.apk
      # artifactType: pipeline

- job: Windows
  displayName: 'Windows'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: FlutterInstall@0

  - task: FlutterBuild@0
    inputs:
      target: windows
      projectDirectory: $(Build.SourcesDirectory)

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/build/windows/runner/Release'
      targetFolder: '$(build.artifactStagingDirectory)'
  
  - task: PublishBuildArtifacts@1
    inputs: 
      pathToPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: Windows


- job: Linux
  displayName: 'Linux'
  pool:
    vmImage: 'ubuntu-20.04'

  steps:
  - task: FlutterInstall@0

  - task: FlutterBuild@0
    inputs:
      target: linux
      projectDirectory: $(Build.SourcesDirectory)

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      targetFolder: '$(build.artifactStagingDirectory)'
  
  - task: PublishBuildArtifacts@1
    inputs: 
      pathToPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: Linux