// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'key_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

KeyModel _$KeyModelFromJson(Map<String, dynamic> json) => KeyModel(
      keyRow: json['keyRow'] as int,
      keyColumn: json['keyColumn'] as int,
      keyCode: $enumDecode(_$KeyCodeEnumMap, json['keyCode']),
      keyWidth: (json['keyWidth'] as num).toDouble(),
      keyHeight: (json['keyHeight'] as num).toDouble(),
      keyRadius: (json['keyRadius'] as num).toDouble(),
      keyLeft: (json['keyLeft'] as num?)?.toDouble() ?? 0,
      keyTop: (json['keyTop'] as num?)?.toDouble() ?? 0,
    );

Map<String, dynamic> _$KeyModelToJson(KeyModel instance) => <String, dynamic>{
      'keyRow': instance.keyRow,
      'keyColumn': instance.keyColumn,
      'keyCode': _$KeyCodeEnumMap[instance.keyCode]!,
      'keyLeft': instance.keyLeft,
      'keyTop': instance.keyTop,
      'keyWidth': instance.keyWidth,
      'keyHeight': instance.keyHeight,
      'keyRadius': instance.keyRadius,
    };

const _$KeyCodeEnumMap = {
  KeyCode.kEsc: 'kEsc',
  KeyCode.kF1: 'kF1',
  KeyCode.kF2: 'kF2',
  KeyCode.kF3: 'kF3',
  KeyCode.kF4: 'kF4',
  KeyCode.kF5: 'kF5',
  KeyCode.kF6: 'kF6',
  KeyCode.kF7: 'kF7',
  KeyCode.kF8: 'kF8',
  KeyCode.kF9: 'kF9',
  KeyCode.kF10: 'kF10',
  KeyCode.kF11: 'kF11',
  KeyCode.kF12: 'kF12',
  KeyCode.kCam: 'kCam',
  KeyCode.kPower: 'kPower',
  KeyCode.kDelete: 'kDelete',
  KeyCode.kTilda: 'kTilda',
  KeyCode.k1: 'k1',
  KeyCode.k2: 'k2',
  KeyCode.k3: 'k3',
  KeyCode.k4: 'k4',
  KeyCode.k5: 'k5',
  KeyCode.k6: 'k6',
  KeyCode.k7: 'k7',
  KeyCode.k8: 'k8',
  KeyCode.k9: 'k9',
  KeyCode.k0: 'k0',
  KeyCode.kDash: 'kDash',
  KeyCode.kEquals: 'kEquals',
  KeyCode.kBackspace: 'kBackspace',
  KeyCode.kTab: 'kTab',
  KeyCode.kQ: 'kQ',
  KeyCode.kW: 'kW',
  KeyCode.kE: 'kE',
  KeyCode.kR: 'kR',
  KeyCode.kT: 'kT',
  KeyCode.kY: 'kY',
  KeyCode.kU: 'kU',
  KeyCode.kI: 'kI',
  KeyCode.kO: 'kO',
  KeyCode.kP: 'kP',
  KeyCode.kBracketLeft: 'kBracketLeft',
  KeyCode.kBracketRight: 'kBracketRight',
  KeyCode.kBackSlash: 'kBackSlash',
  KeyCode.kCaps: 'kCaps',
  KeyCode.kA: 'kA',
  KeyCode.kS: 'kS',
  KeyCode.kD: 'kD',
  KeyCode.kF: 'kF',
  KeyCode.kG: 'kG',
  KeyCode.kH: 'kH',
  KeyCode.kJ: 'kJ',
  KeyCode.kK: 'kK',
  KeyCode.kL: 'kL',
  KeyCode.kColon: 'kColon',
  KeyCode.kQuote: 'kQuote',
  KeyCode.kEnter: 'kEnter',
  KeyCode.kShiftLeft: 'kShiftLeft',
  KeyCode.kZ: 'kZ',
  KeyCode.kX: 'kX',
  KeyCode.kC: 'kC',
  KeyCode.kV: 'kV',
  KeyCode.kB: 'kB',
  KeyCode.kN: 'kN',
  KeyCode.kM: 'kM',
  KeyCode.kComma: 'kComma',
  KeyCode.kPeriod: 'kPeriod',
  KeyCode.kForwardSlash: 'kForwardSlash',
  KeyCode.kShiftRight: 'kShiftRight',
  KeyCode.kCtrlLeft: 'kCtrlLeft',
  KeyCode.kFn: 'kFn',
  KeyCode.kWin: 'kWin',
  KeyCode.kAltLeft: 'kAltLeft',
  KeyCode.kSpacebar: 'kSpacebar',
  KeyCode.kAltRight: 'kAltRight',
  KeyCode.kCrtlRight: 'kCrtlRight',
  KeyCode.kArrowLeft: 'kArrowLeft',
  KeyCode.kArrowUp: 'kArrowUp',
  KeyCode.kArrowDown: 'kArrowDown',
  KeyCode.kArrowRight: 'kArrowRight',
};
